name: "Balto - Eslint"
description: "Run eslint on your repo"
runs:
  using: node12
  main: main.js
branding:
  icon: life-buoy
  color: orange
inputs:
  extensions:
    description: "A comma separated list of extensions to run on"
    require: false
    default: "js"
  conclusionLevel:
    description: 'Which check run conclusion type to use when annotations are created ("neutral" or "failure" are most common)'
    required: false
    default: "neutral"
  dependencies:
    description: 'An JSON-encoded array of dependencies (other than `eslint`) that `eslint` requires in order to complete the check'
    required: false
    default: '[]'
outputs:
  issuesCount:
    description: "Number of eslint violations found"
