name: "Balto - ESLint"
description: "Run ESLint on your repo"
runs:
  using: node20
  main: dist/index.js
branding:
  icon: life-buoy
  color: orange
inputs:
  failure-level:
    description: 'The lowest annotation level to fail on ("warning" or "error")'
    required: false
    default: "error"
  conclusion-level:
    description: 'Action conclusion ("success" or "failure") if annotations of the failure-level were created'
    required: false
    default: "success"
  working-directory:
    description: Which directory to run the action in
    required: false
    default: "."
outputs:
  warning-count:
    description: "Number of relevant warnings found"
  error-count:
    description: "Number of relevant errors found"
  total-count:
    description: "Number of relevant warnings and errors"
